version: '3.8'

name: rails-starterpack-production

services:
  db:
    image: postgres
    volumes:
      - ../production_data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build:
      context: ..
      dockerfile: '.docker-prod/Dockerfile'
    command: 'sh .docker-prod/entrypoint.sh'
    volumes: 
      - ../tmp/bundle:/usr/local/bundle
    env_file:
      - ../.env
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db
    restart: unless-stopped
