name: CI

on:
  push:
  workflow_dispatch: # Allows manually triggering (only mantainers can do this)

env:
  COMPOSE_FILE: .docker/docker-compose.yml
  RAILS_ENV: test

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: touch .env && docker compose run --rm web bundle install
      - name: Create Database
        run: docker compose run --rm web bash -c "RAILS_ENV=test bundle exec rails db:create"
      - name: Chmod it all!
        run: chmod 777 -R production_data
      - name: Save to artifiact
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifact
          path: .

  test:
    runs-on: ubuntu-latest

    needs: setup
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ci-artifact
      - name: Test
        run: docker compose run --rm web bundle exec rails test:all

  standardrb:
    runs-on: ubuntu-latest

    needs: setup
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ci-artifact
      - name: Standardrb
        run: docker compose run --rm web bundle exec standardrb
