name: CI

on:
  push:
  workflow_dispatch: # Allows manually triggering (only mantainers can do this)

jobs:
  test:
    runs-on: debian-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: docker compose run --rm web bundle exec rails test:all
