name: CI

on:
  push:
  workflow_dispatch: # Allows manually triggering (only mantainers can do this)

env:
  COMPOSE_FILE: .docker/docker-compose.yml
  RAILS_ENV: development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: docker compose run --rm web bundle exec rails test:all
